# 应用程序配置

# 应用程序基本信息
APP_TITLE = "基金考试题库系统 — BY Sylvan_930"
WINDOW_SIZE = "900x700"

# UI配置
UI_FONT_FAMILY = "微软雅黑"
UI_QUESTION_FONT_SIZE = 14
UI_OPTION_FONT_SIZE = 12
UI_NORMAL_FONT_SIZE = 10
UI_FEEDBACK_FONT_SIZE = 12
UI_EXPLANATION_FONT_SIZE = 11

# 颜色配置
COLOR_CORRECT = "green"
COLOR_INCORRECT = "red"
COLOR_BACKGROUND = "#f5f5f5"
COLOR_STATUS_TEXT = "#666666"

# 文件配置
FILE_PATTERNS = ['.docx', '.txt', '.csv']

# 日志配置
LOG_LEVEL = "INFO"
LOG_FILE = "quiz_bank.log"